# Generated by Django 4.2.7 on 2024-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_type",
            field=models.CharField(
                choices=[
                    ("HC", "Твёрдый переплёт"),
                    ("PB", "Мягкий переплёт"),
                    ("EB", "Электроная книга"),
                ],
                default="PB",
                max_length=2,
            ),
        ),
    ]
