# Generated by Django 4.2.11 on 2024-03-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(to="books.tag"),
        ),
    ]
